require 'active_support/inflector'

# All components of the RSVP core library must use the core namespace `Rsvp`.
module Rsvp

  # Constructs Schema objects from a variety of source formats.
  class Generator
    # Intercepts all `from_*` method calls to the generator. Using the method
    # name, the generator will attempt to load the appropriate file, create a
    # parser, and generate a schema object. If a block is used, the schema
    # object is passed to the block on invocation; otherwise the schema object
    # is returned to the caller.
    #
    # @param method (Symbol) intercepts any method starting with "from_".
    # @param *args (Array) an argument array, passed to the `new` method when
    #   constructing a parser object.
    # @param &block (Block) if supplied, the schema object generated by the
    #   parser is passed in to `block.call`.
    #
    # @return (Rsvp::Schema,Object) if no block is given, a schema object is
    #   returned; otherwise the output from the block is returned.
    def self.method_missing(method, *args, &block)
      mstr = method.to_s
      if mstr.start_with?("from_")
        # Require the appropriate parser
        file = "lib/rsvp/parsers/#{mstr[5..-1]}"
        require file
        # Construct a new Schema object using the parser
        cls = file.camelize.constantize
        schema = cls.send(:new, *args)
        if block
          block.call(schema)
        else
          schema
        end
      end
    end
  end

end
